---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local 
  tasks:
    # Galaxy is not responsible for installing modules requirements
    - name: Install playbook requirements
      pip:
        name:
          - scipy
          - matplotlib
        extra_args: --user
    - name: Run the Pystol module to kill some random pods
      pystol.actions.kill_pods:
        namespace: "{{ pystol_killpods_namespace }}"
        distribution: "{{ pystol_killpods_distribution }}"
        amount: "{{ pystol_killpods_amount }}"
      register: testout
    - debug: msg="{{ testout.stderr }}"
    - debug: msg="{{ testout.stdout }}"
    - debug: msg="{{ testout }}"
      # Here we make the task fail
      # depending on the action execution
      # ALL METHODS SHOULD RETURN STDERR AND STDOUT
      failed_when: >
        (testout.stderr | length > 0) or
        (testout.rc == 10)
