namespace: "pystol"
name: "actions"
version: "0.1.6"
description: "Pystol native actions"
authors: ["Carlos Camacho>"]
license: ["Apache-2.0"]
readme: README.md
tags:
  - pystol
  - fault_injection
  - chaos_engineering
repository: "https://github.com/pystol/pystol-galaxy"
