namespace: "pystol"
name: "actions"
version: "0.1.0"
description: "Pystol native actions"
authors: ["Carlos Camacho>"]
license: ["Apache"]
readme: README.md
tags:
  - pystol
  - fault-injection
  - chaos-engineering
repository: "https://github.com/pystol/pystol-galaxy"
